name: ljubavnikalkulator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic_plus: ^3.5.0
  flutter_typeahead: ^5.2.0
  http: ^1.6.0
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  sweph: ^3.2.1+2.10.3  # NASA/Swiss Ephemeris preciznost
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  lunar: ^1.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
